### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by agungadhika** [agungadhika/Dejection#19]
1. Memberikan payload kepada inputan yang udah ada isinya
2. Payload pada NoSQL Injection, dikarenakan menggunakan format json
3. Update POST Method Input nya ada Input type select bukan hanya input biasa
4. bad escape \u at position 26 -> Error ketika jalanin xss, benerin RegEx nya

**Comment by Agung-Krisna** [comment]
Number 3 is done

**Comment by agungadhika** [comment]
All done
