### ISSUE TITLE
Permasalahan aplikasi

### ISSUE THREAD

**Issue by agungadhika** [agungadhika/Dejection#9]
1. Infinite Loop saat pengiriman payload
2. Data di result bisa di print pdf
3. Bypass login DVWA agar bisa testing disana
4. Payload yang ada masih sedikit

**Comment by Agung-Krisna** [comment]
Point number two done

**Comment by agungadhika** [comment]
Number 1 & 3 Done. Next Split POST Method and redirect to loading page.
